language: java
dist: trusty
sudo: false
jdk:
  - oraclejdk8
before_install:
- chmod +x mvnw
services:
    - postgresql
before_script:
    - psql -c 'CREATE DATABASE bancoSistex;' -U postgres;
    - psql -c "ALTER USER postgres WITH PASSWORD 'ifes'" -d template1;
addons:
  sonarcloud:
    organization: "penaspenas123"
    token:
      secure: "$SONAR_PASSWORD"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
deploy:
 provider: heroku
 api-key:
  secure: $API_KEY_HEROKU
 app: servicocontrolepedidos
